// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GameEvent      string
	Player         string
	Role           string
	TemplateHeader string
	TemplateRole   string
	VoteHistory    string
}{
	GameEvent:      "game_event",
	Player:         "player",
	Role:           "role",
	TemplateHeader: "template_header",
	TemplateRole:   "template_role",
	VoteHistory:    "vote_history",
}
