package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"

	"github.com/thomas81528262/wolf/golang-server/apimodels"
	graph "github.com/thomas81528262/wolf/golang-server/graph/generated"
	"github.com/thomas81528262/wolf/golang-server/service"
)

// GetRolesByID is the resolver for the getRolesById field.
func (r *queryResolver) GetRolesByID(ctx context.Context, input apimodels.GetRolesInput) (*apimodels.GetRolesResponse, error) {
	return service.GetRolesByID(ctx, input)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
