// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package apimodels

type GetRolesInput struct {
	Ids []int `json:"ids"`
}

type GetRolesResponse struct {
	Roles []*Role `json:"Roles"`
}

type Role struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
