// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package apimodels

type GetRolesInput struct {
	ID []*string `json:"id"`
}

type GetRolesResponse struct {
	Roles []*Role `json:"Roles"`
}

type Role struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
