name: build
run-name: build 🚀
on: [push]
jobs:
  Build-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
      working-directory: ./server
    - run: npm run build
      working-directory: ./server
      